// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

// Protobuf Java Version: 3.25.3
package io.tryrook.rook_sdk.proto;

public interface MissingAndroidPermissionsExceptionProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MissingAndroidPermissionsExceptionProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
