// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

// Protobuf Java Version: 3.25.3
package io.tryrook.rook_sdk.proto;

public final class ProtobufModels {
  private ProtobufModels() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeviceNotSupportedExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeviceNotSupportedExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HealthConnectNotInstalledExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HealthConnectNotInstalledExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HttpRequestExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HttpRequestExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MissingConfigurationExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MissingConfigurationExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MissingPermissionsExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MissingPermissionsExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestQuotaExceededExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestQuotaExceededExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SDKNotInitializedExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SDKNotInitializedExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeoutExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeoutExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserNotInitializedExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserNotInitializedExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GenericExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GenericExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MissingAndroidPermissionsExceptionProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MissingAndroidPermissionsExceptionProto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResultBooleanProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResultBooleanProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014protos.proto\"3\n DeviceNotSupportedExce" +
      "ptionProto\022\017\n\007message\030\001 \001(\t\":\n\'HealthCon" +
      "nectNotInstalledExceptionProto\022\017\n\007messag" +
      "e\030\001 \001(\t\":\n\031HttpRequestExceptionProto\022\017\n\007" +
      "message\030\001 \001(\t\022\014\n\004code\030\002 \001(\r\"5\n\"MissingCo" +
      "nfigurationExceptionProto\022\017\n\007message\030\001 \001" +
      "(\t\"3\n MissingPermissionsExceptionProto\022\017" +
      "\n\007message\030\001 \001(\t\"5\n\"RequestQuotaExceededE" +
      "xceptionProto\022\017\n\007message\030\001 \001(\t\"2\n\037SDKNot" +
      "InitializedExceptionProto\022\017\n\007message\030\001 \001" +
      "(\t\"(\n\025TimeoutExceptionProto\022\017\n\007message\030\001" +
      " \001(\t\"3\n UserNotInitializedExceptionProto" +
      "\022\017\n\007message\030\001 \001(\t\"(\n\025GenericExceptionPro" +
      "to\022\017\n\007message\030\001 \001(\t\":\n\'MissingAndroidPer" +
      "missionsExceptionProto\022\017\n\007message\030\001 \001(\t\"" +
      "\376\006\n\022ResultBooleanProto\022\021\n\007success\030\001 \001(\010H" +
      "\000\022M\n deviceNotSupportedExceptionProto\030\002 " +
      "\001(\0132!.DeviceNotSupportedExceptionProtoH\000" +
      "\022[\n\'healthConnectNotInstalledExceptionPr" +
      "oto\030\003 \001(\0132(.HealthConnectNotInstalledExc" +
      "eptionProtoH\000\022?\n\031httpRequestExceptionPro" +
      "to\030\004 \001(\0132\032.HttpRequestExceptionProtoH\000\022Q" +
      "\n\"missingConfigurationExceptionProto\030\005 \001" +
      "(\0132#.MissingConfigurationExceptionProtoH" +
      "\000\022M\n missingPermissionsExceptionProto\030\006 " +
      "\001(\0132!.MissingPermissionsExceptionProtoH\000" +
      "\022Q\n\"requestQuotaExceededExceptionProto\030\007" +
      " \001(\0132#.RequestQuotaExceededExceptionProt" +
      "oH\000\022K\n\037sdkNotInitializedExceptionProto\030\010" +
      " \001(\0132 .SDKNotInitializedExceptionProtoH\000" +
      "\0227\n\025timeoutExceptionProto\030\t \001(\0132\026.Timeou" +
      "tExceptionProtoH\000\022M\n userNotInitializedE" +
      "xceptionProto\030\n \001(\0132!.UserNotInitialized" +
      "ExceptionProtoH\000\0227\n\025genericExceptionProt" +
      "o\030\013 \001(\0132\026.GenericExceptionProtoH\000\022[\n\'mis" +
      "singAndroidPermissionsExceptionProto\030\014 \001" +
      "(\0132(.MissingAndroidPermissionsExceptionP" +
      "rotoH\000B\010\n\006result*C\n\025HealthPermissionProt" +
      "o\022\t\n\005SLEEP\020\000\022\014\n\010PHYSICAL\020\001\022\010\n\004BODY\020\002\022\007\n\003" +
      "ALL\020\003B-\n\031io.tryrook.rook_sdk.protoB\016Prot" +
      "obufModelsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DeviceNotSupportedExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DeviceNotSupportedExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeviceNotSupportedExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_HealthConnectNotInstalledExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HealthConnectNotInstalledExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HealthConnectNotInstalledExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_HttpRequestExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HttpRequestExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HttpRequestExceptionProto_descriptor,
        new java.lang.String[] { "Message", "Code", });
    internal_static_MissingConfigurationExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_MissingConfigurationExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MissingConfigurationExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_MissingPermissionsExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_MissingPermissionsExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MissingPermissionsExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_RequestQuotaExceededExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_RequestQuotaExceededExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestQuotaExceededExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_SDKNotInitializedExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_SDKNotInitializedExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SDKNotInitializedExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_TimeoutExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TimeoutExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeoutExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_UserNotInitializedExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UserNotInitializedExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserNotInitializedExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GenericExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_GenericExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GenericExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_MissingAndroidPermissionsExceptionProto_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_MissingAndroidPermissionsExceptionProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MissingAndroidPermissionsExceptionProto_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ResultBooleanProto_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ResultBooleanProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResultBooleanProto_descriptor,
        new java.lang.String[] { "Success", "DeviceNotSupportedExceptionProto", "HealthConnectNotInstalledExceptionProto", "HttpRequestExceptionProto", "MissingConfigurationExceptionProto", "MissingPermissionsExceptionProto", "RequestQuotaExceededExceptionProto", "SdkNotInitializedExceptionProto", "TimeoutExceptionProto", "UserNotInitializedExceptionProto", "GenericExceptionProto", "MissingAndroidPermissionsExceptionProto", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
