// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos.proto

// Protobuf Java Version: 3.25.3
package io.tryrook.rook_sdk.proto;

public interface ResultBooleanProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResultBooleanProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.DeviceNotSupportedExceptionProto deviceNotSupportedExceptionProto = 2;</code>
   * @return Whether the deviceNotSupportedExceptionProto field is set.
   */
  boolean hasDeviceNotSupportedExceptionProto();
  /**
   * <code>.DeviceNotSupportedExceptionProto deviceNotSupportedExceptionProto = 2;</code>
   * @return The deviceNotSupportedExceptionProto.
   */
  io.tryrook.rook_sdk.proto.DeviceNotSupportedExceptionProto getDeviceNotSupportedExceptionProto();
  /**
   * <code>.DeviceNotSupportedExceptionProto deviceNotSupportedExceptionProto = 2;</code>
   */
  io.tryrook.rook_sdk.proto.DeviceNotSupportedExceptionProtoOrBuilder getDeviceNotSupportedExceptionProtoOrBuilder();

  /**
   * <code>.HealthConnectNotInstalledExceptionProto healthConnectNotInstalledExceptionProto = 3;</code>
   * @return Whether the healthConnectNotInstalledExceptionProto field is set.
   */
  boolean hasHealthConnectNotInstalledExceptionProto();
  /**
   * <code>.HealthConnectNotInstalledExceptionProto healthConnectNotInstalledExceptionProto = 3;</code>
   * @return The healthConnectNotInstalledExceptionProto.
   */
  io.tryrook.rook_sdk.proto.HealthConnectNotInstalledExceptionProto getHealthConnectNotInstalledExceptionProto();
  /**
   * <code>.HealthConnectNotInstalledExceptionProto healthConnectNotInstalledExceptionProto = 3;</code>
   */
  io.tryrook.rook_sdk.proto.HealthConnectNotInstalledExceptionProtoOrBuilder getHealthConnectNotInstalledExceptionProtoOrBuilder();

  /**
   * <code>.HttpRequestExceptionProto httpRequestExceptionProto = 4;</code>
   * @return Whether the httpRequestExceptionProto field is set.
   */
  boolean hasHttpRequestExceptionProto();
  /**
   * <code>.HttpRequestExceptionProto httpRequestExceptionProto = 4;</code>
   * @return The httpRequestExceptionProto.
   */
  io.tryrook.rook_sdk.proto.HttpRequestExceptionProto getHttpRequestExceptionProto();
  /**
   * <code>.HttpRequestExceptionProto httpRequestExceptionProto = 4;</code>
   */
  io.tryrook.rook_sdk.proto.HttpRequestExceptionProtoOrBuilder getHttpRequestExceptionProtoOrBuilder();

  /**
   * <code>.MissingConfigurationExceptionProto missingConfigurationExceptionProto = 5;</code>
   * @return Whether the missingConfigurationExceptionProto field is set.
   */
  boolean hasMissingConfigurationExceptionProto();
  /**
   * <code>.MissingConfigurationExceptionProto missingConfigurationExceptionProto = 5;</code>
   * @return The missingConfigurationExceptionProto.
   */
  io.tryrook.rook_sdk.proto.MissingConfigurationExceptionProto getMissingConfigurationExceptionProto();
  /**
   * <code>.MissingConfigurationExceptionProto missingConfigurationExceptionProto = 5;</code>
   */
  io.tryrook.rook_sdk.proto.MissingConfigurationExceptionProtoOrBuilder getMissingConfigurationExceptionProtoOrBuilder();

  /**
   * <code>.MissingPermissionsExceptionProto missingPermissionsExceptionProto = 6;</code>
   * @return Whether the missingPermissionsExceptionProto field is set.
   */
  boolean hasMissingPermissionsExceptionProto();
  /**
   * <code>.MissingPermissionsExceptionProto missingPermissionsExceptionProto = 6;</code>
   * @return The missingPermissionsExceptionProto.
   */
  io.tryrook.rook_sdk.proto.MissingPermissionsExceptionProto getMissingPermissionsExceptionProto();
  /**
   * <code>.MissingPermissionsExceptionProto missingPermissionsExceptionProto = 6;</code>
   */
  io.tryrook.rook_sdk.proto.MissingPermissionsExceptionProtoOrBuilder getMissingPermissionsExceptionProtoOrBuilder();

  /**
   * <code>.RequestQuotaExceededExceptionProto requestQuotaExceededExceptionProto = 7;</code>
   * @return Whether the requestQuotaExceededExceptionProto field is set.
   */
  boolean hasRequestQuotaExceededExceptionProto();
  /**
   * <code>.RequestQuotaExceededExceptionProto requestQuotaExceededExceptionProto = 7;</code>
   * @return The requestQuotaExceededExceptionProto.
   */
  io.tryrook.rook_sdk.proto.RequestQuotaExceededExceptionProto getRequestQuotaExceededExceptionProto();
  /**
   * <code>.RequestQuotaExceededExceptionProto requestQuotaExceededExceptionProto = 7;</code>
   */
  io.tryrook.rook_sdk.proto.RequestQuotaExceededExceptionProtoOrBuilder getRequestQuotaExceededExceptionProtoOrBuilder();

  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   * @return Whether the sdkNotInitializedExceptionProto field is set.
   */
  boolean hasSdkNotInitializedExceptionProto();
  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   * @return The sdkNotInitializedExceptionProto.
   */
  io.tryrook.rook_sdk.proto.SDKNotInitializedExceptionProto getSdkNotInitializedExceptionProto();
  /**
   * <code>.SDKNotInitializedExceptionProto sdkNotInitializedExceptionProto = 8;</code>
   */
  io.tryrook.rook_sdk.proto.SDKNotInitializedExceptionProtoOrBuilder getSdkNotInitializedExceptionProtoOrBuilder();

  /**
   * <code>.TimeoutExceptionProto timeoutExceptionProto = 9;</code>
   * @return Whether the timeoutExceptionProto field is set.
   */
  boolean hasTimeoutExceptionProto();
  /**
   * <code>.TimeoutExceptionProto timeoutExceptionProto = 9;</code>
   * @return The timeoutExceptionProto.
   */
  io.tryrook.rook_sdk.proto.TimeoutExceptionProto getTimeoutExceptionProto();
  /**
   * <code>.TimeoutExceptionProto timeoutExceptionProto = 9;</code>
   */
  io.tryrook.rook_sdk.proto.TimeoutExceptionProtoOrBuilder getTimeoutExceptionProtoOrBuilder();

  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   * @return Whether the userNotInitializedExceptionProto field is set.
   */
  boolean hasUserNotInitializedExceptionProto();
  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   * @return The userNotInitializedExceptionProto.
   */
  io.tryrook.rook_sdk.proto.UserNotInitializedExceptionProto getUserNotInitializedExceptionProto();
  /**
   * <code>.UserNotInitializedExceptionProto userNotInitializedExceptionProto = 10;</code>
   */
  io.tryrook.rook_sdk.proto.UserNotInitializedExceptionProtoOrBuilder getUserNotInitializedExceptionProtoOrBuilder();

  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   * @return Whether the genericExceptionProto field is set.
   */
  boolean hasGenericExceptionProto();
  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   * @return The genericExceptionProto.
   */
  io.tryrook.rook_sdk.proto.GenericExceptionProto getGenericExceptionProto();
  /**
   * <code>.GenericExceptionProto genericExceptionProto = 11;</code>
   */
  io.tryrook.rook_sdk.proto.GenericExceptionProtoOrBuilder getGenericExceptionProtoOrBuilder();

  /**
   * <code>.MissingAndroidPermissionsExceptionProto missingAndroidPermissionsExceptionProto = 12;</code>
   * @return Whether the missingAndroidPermissionsExceptionProto field is set.
   */
  boolean hasMissingAndroidPermissionsExceptionProto();
  /**
   * <code>.MissingAndroidPermissionsExceptionProto missingAndroidPermissionsExceptionProto = 12;</code>
   * @return The missingAndroidPermissionsExceptionProto.
   */
  io.tryrook.rook_sdk.proto.MissingAndroidPermissionsExceptionProto getMissingAndroidPermissionsExceptionProto();
  /**
   * <code>.MissingAndroidPermissionsExceptionProto missingAndroidPermissionsExceptionProto = 12;</code>
   */
  io.tryrook.rook_sdk.proto.MissingAndroidPermissionsExceptionProtoOrBuilder getMissingAndroidPermissionsExceptionProtoOrBuilder();

  io.tryrook.rook_sdk.proto.ResultBooleanProto.ResultCase getResultCase();
}
