name: rook_sdk
description: This package enables apps to extract and upload data from Health Connect and Apple Health.
version: 0.0.1
homepage: 'https://docs.tryrook.io/'
platforms:
  android:
  ios:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.tryrook.rook_sdk
        pluginClass: RookSdkPlugin
      ios:
        pluginClass: RookSdkPlugin