name: global CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  rook_sdk_core_format:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format packages/rook_sdk_core -o none --set-exit-if-changed

  rook_sdk_core_analyze:
    needs: [ rook_sdk_core_format ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: dart analyze packages/rook_sdk_core --fatal-infos

  rook_sdk_core_pana:
    needs: [ rook_sdk_core_analyze ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install pana
        run: dart pub global activate pana

      - name: Create reports directory
        run: mkdir reports

      - name: Run pana
        run: pana packages/rook_sdk_core |& tee reports/pana.txt

      - name: Upload pana report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: pana-report.txt
          path: reports/pana.txt

  rook_sdk_core_test:
    needs: [ rook_sdk_core_pana]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create reports directory
        run: mkdir reports

      - name: Run tests
        run: cd packages/rook_sdk_core && flutter test --file-reporter github:reports/test.txt

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test-report.txt
          path: packages/rook_sdk_core/reports/test.txt

  rook_sdk_apple_health_format:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format packages/rook_sdk_apple_health -o none --set-exit-if-changed

  rook_sdk_apple_health_analyze:
    needs: [ rook_sdk_apple_health_format ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: dart analyze packages/rook_sdk_apple_health --fatal-infos

  rook_sdk_apple_health_pana:
    needs: [ rook_sdk_apple_health_analyze ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install pana
        run: dart pub global activate pana

      - name: Create reports directory
        run: mkdir reports

      - name: Run pana
        run: pana packages/rook_sdk_apple_health |& tee reports/pana.txt

      - name: Upload pana report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: pana-report.txt
          path: reports/pana.txt

  rook_sdk_apple_health_test:
    needs: [ rook_sdk_apple_health_pana]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create reports directory
        run: mkdir reports

      - name: Run tests
        run: cd packages/rook_sdk_apple_health && flutter test --file-reporter github:reports/test.txt

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test-report.txt
          path: packages/rook_sdk_apple_health/reports/test.txt

  rook_sdk_health_connect_format:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format packages/rook_sdk_health_connect -o none --set-exit-if-changed

  rook_sdk_health_connect_analyze:
    needs: [ rook_sdk_health_connect_format ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer
        run: dart analyze packages/rook_sdk_health_connect --fatal-infos

  rook_sdk_health_connect_pana:
    needs: [ rook_sdk_health_connect_analyze ]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install pana
        run: dart pub global activate pana

      - name: Create reports directory
        run: mkdir reports

      - name: Run pana
        run: pana packages/rook_sdk_health_connect |& tee reports/pana.txt

      - name: Upload pana report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: pana-report.txt
          path: reports/pana.txt

  rook_sdk_health_connect_test:
    needs: [ rook_sdk_health_connect_pana]
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Create reports directory
        run: mkdir reports

      - name: Run tests
        run: cd packages/rook_sdk_health_connect && flutter test --file-reporter github:reports/test.txt

      - name: Upload test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: test-report.txt
          path: packages/rook_sdk_health_connect/reports/test.txt